### ISSUE TITLE
Neutral monster

### ISSUE THREAD

**Issue by BarbaraMMCS** [ptal/lol2D#42]
We could add a neutral dragon that randomly attacks all champions that are too close. The dragon doesn't move.

sprite:
https://www.subpng.com/png-bni7rl/

We could add later on a boost for the team that kills the dragon.

**Comment by BarbaraMMCS** [comment]
I added another monster: nashor.

sprite :
https://www.pinclipart.com/pindetail/iihibJw_fan-art-of-baron-from-league-of-legends/

**Comment by ptal** [comment]
It was closed by pull request #44
